### ISSUE TITLE
nearby line window calling wrong ion

### ISSUE THREAD

**Issue by Morisset** [Morisset/pySSN#21]
Select a wavelength range that includes 4959 and 5007.
In the popup window of the nearby lines, click on the [OIII]5007 line ID (8033400004003): it opens the OIII line info dialog. That's OK.
But click on the [OIII]4959 line ID (8033400004002), it opens the ArIII line info dialog!

**Comment by mvfcopetti** [comment]
Change lines 1298 to 1300 in spectrum.py by:

		    s = str(int(s))
                    if (int(s) == line_num) or (s[:k] == line_num_str and s[k:].strip('0') == ''):

**Comment by mvfcopetti** [comment]
In the previous message there was a wrong indentation (Tabs again).

Right indentation:

                    s = str(int(s))
                    if (int(s) == line_num) or (s[:k] == line_num_str and s[k:].strip('0') == ''):

**Comment by Morisset** [comment]
We actually removed lines there because they were buggy.
These new ones have an horrible look, but works well ;-)
