### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by Morisset** [Morisset/pySSN#8]
File "/Users/christophemorisset/anaconda/envs/py3k5qt4/lib/python3.5/site-packages/pyssn/qt/pyssn_qt.py", line 681, in create_menu
    s = s + '    ' + str(i) + ' - ' + items[i] + '\n'
TypeError: 'odict_values' object does not support indexing

**Comment by mvfcopetti** [comment]
In line 659,
items = list(self.line_print_dic.values()) 
does not solve the problem?

**Comment by Morisset** [comment]
OK, Thanks.
The main issue with python 3 is actually the default Qt version, changing from 4 to 5.
This will be another (big) issue.
